"""
Persist simulated device state to the Shepherd database.

This module contains the repository responsible for converting
DeviceState objects produced by the simulation layer into SQLAlchemy
Device ORM objects and persisting them in PostgreSQL.
"""

from database.models import Device
from database.session import SessionLocal
from simulation.device_state import DeviceState


def save_devices(
    devices: list[DeviceState],
    batch_size: int = 1000,
) -> int:
    """
    Persist simulated devices to PostgreSQL.

    Devices are inserted in batches to avoid constructing one extremely
    large SQLAlchemy unit of work when the simulation population grows.

    Parameters
    ----------
    devices:
        DeviceState objects generated by the simulation.
    batch_size:
        Maximum number of devices to add to a session before flushing.

    Returns
    -------
    int
        Number of device records successfully persisted.

    Raises
    ------
    ValueError
        If batch_size is less than or equal to zero.
    """

    if batch_size <= 0:
        raise ValueError("batch_size must be greater than zero")

    if not devices:
        return 0

    total_saved = 0

    with SessionLocal() as session:
        for start in range(0, len(devices), batch_size):
            batch = devices[start : start + batch_size]

            device_rows = [
                Device(
                    device_id=device.device_id,
                    customer_id=device.customer_id,
                    device_trust_score=device.device_trust_score,
                    first_seen=device.first_seen,
                )
                for device in batch
            ]

            session.add_all(device_rows)
            session.flush()

            total_saved += len(device_rows)

        session.commit()

    return total_saved