"""
Persist simulated device state to the Shepherd database.

This module contains the repository responsible for converting
DeviceState objects produced by the simulation layer into SQLAlchemy
Device ORM objects and persisting them in PostgreSQL.
"""

from simulation.device_state import DeviceState
from database.models import Device
from database.session import SessionLocal


def save_devices(
    devices: list[DeviceState],
    batch_size: int = 1000,
) -> None:
    """
    Persist simulated devices to PostgreSQL.

    Devices are inserted in batches to avoid constructing one extremely
    large SQLAlchemy unit of work when the simulation population grows.

    Parameters
    ----------
    devices:
        DeviceState objects generated by the simulation.
    batch_size:
        Maximum number of devices to add to a session before flushing.
        The transaction is committed once after all batches have been
        processed.

    Returns
    -------
    None
    """

    if not devices:
        return

    with SessionLocal() as session:
        for start in range(0, len(devices), batch_size):
            batch = devices[start : start + batch_size]

            session.add_all(
                [
                    Device(
                        device_id=device.device_id,
                        customer_id=device.customer_id,
                        device_trust_score=device.device_trust_score,
                        first_seen=device.first_seen,
                    )
                    for device in batch
                ]
            )

            session.flush()

        session.commit()