"""
Persist simulated merchant state to the Shepherd database.

This module converts MerchantState objects produced by the simulation layer
into SQLAlchemy Merchant ORM objects and persists them in PostgreSQL.
"""

from database.models import Merchant
from database.session import SessionLocal
from simulation.merchant_state import MerchantState


def save_merchants(
    merchants: list[MerchantState],
    batch_size: int = 1000,
) -> int:
    """
    Persist simulated merchants to PostgreSQL.

    Merchants are inserted in batches so that the repository remains suitable
    for larger simulation populations.

    Parameters
    ----------
    merchants:
        MerchantState objects generated by the simulation layer.
    batch_size:
        Maximum number of merchants inserted in a single batch.

    Returns
    -------
    int
        Number of merchant records successfully persisted.

    Raises
    ------
    ValueError
        If batch_size is less than or equal to zero.
    """

    if batch_size <= 0:
        raise ValueError(
            "batch_size must be greater than zero"
        )

    if not merchants:
        return 0

    total_saved = 0

    with SessionLocal() as session:
        for start in range(
            0,
            len(merchants),
            batch_size,
        ):
            batch = merchants[
                start:start + batch_size
            ]

            merchant_rows = [
                Merchant(
                    merchant_id=merchant.merchant_id,
                    merchant_name=merchant.merchant_name,
                    merchant_category=merchant.merchant_category,
                    merchant_country=merchant.merchant_country,
                    risk_score=merchant.risk_score,
                )
                for merchant in batch
            ]

            session.add_all(merchant_rows)
            session.flush()

            total_saved += len(merchant_rows)

        session.commit()

    return total_saved