"""
Persist the complete Shepherd simulation population.

This module coordinates persistence of customers, accounts, and devices
generated by PopulationBuilder.

Entities are persisted in dependency order so that PostgreSQL foreign-key
constraints are satisfied.
"""

from simulation.account_repository import save_accounts
from simulation.customer_repository import save_customers
from simulation.device_repository import save_devices
from simulation.population_builder import Population


def save_population(population: Population) -> None:
    """
    Persist a complete simulation population to PostgreSQL.

    Customers are written first because accounts and devices reference them.
    Accounts are written next, followed by devices.

    Parameters
    ----------
    population:
        Complete in-memory simulation population produced by
        PopulationBuilder.

    Returns
    -------
    None

    Raises
    ------
    RuntimeError
        If the number of persisted records does not match the generated
        population.
    """

    customers_saved = save_customers(population.customers)
    accounts_saved = save_accounts(population.accounts)
    devices_saved = save_devices(population.devices)

    if customers_saved != len(population.customers):
        raise RuntimeError(
            f"Expected to save {len(population.customers)} customers, "
            f"but saved {customers_saved}."
        )

    if accounts_saved != len(population.accounts):
        raise RuntimeError(
            f"Expected to save {len(population.accounts)} accounts, "
            f"but saved {accounts_saved}."
        )

    if devices_saved != len(population.devices):
        raise RuntimeError(
            f"Expected to save {len(population.devices)} devices, "
            f"but saved {devices_saved}."
        )