"""
Persist simulated transaction state to the Shepherd database.

This module converts TransactionState objects produced by the simulation
layer into SQLAlchemy Transaction ORM objects and persists them in PostgreSQL
using batched inserts.

The repository deliberately does not generate transactions. Its responsibility
is limited to translating simulation state into database records and
persisting those records reliably.
"""

from database.models import Transaction
from database.session import SessionLocal
from simulation.transaction_state import TransactionState


def save_transactions(
    transactions: list[TransactionState],
    batch_size: int = 1000,
) -> int:
    """
    Persist simulated transactions to PostgreSQL.

    Transactions are inserted in batches so the repository can handle large
    simulation populations without creating one unnecessarily large
    SQLAlchemy unit of work.

    Parameters
    ----------
    transactions:
        TransactionState objects generated by the simulation layer.
    batch_size:
        Maximum number of transactions to add to the session before flushing.

    Returns
    -------
    int
        Number of transaction records successfully persisted.

    Raises
    ------
    ValueError
        If batch_size is less than or equal to zero.
    """

    if batch_size <= 0:
        raise ValueError(
            "batch_size must be greater than zero"
        )

    if not transactions:
        return 0

    total_saved = 0

    with SessionLocal() as session:
        for start in range(
            0,
            len(transactions),
            batch_size,
        ):
            batch = transactions[
                start:start + batch_size
            ]

            transaction_rows = [
                Transaction(
                    transaction_id=transaction.transaction_id,
                    account_id=transaction.account_id,
                    merchant_id=transaction.merchant_id,
                    device_id=transaction.device_id,
                    amount=transaction.amount,
                    currency=transaction.currency,
                    transaction_timestamp=(
                        transaction.transaction_timestamp
                    ),
                    transaction_country=(
                        transaction.transaction_country
                    ),
                    ip_address=str(
                        transaction.ip_address
                    ),
                    is_fraud=transaction.is_fraud,
                )
                for transaction in batch
            ]

            session.add_all(transaction_rows)
            session.flush()

            total_saved += len(transaction_rows)

        session.commit()

    return total_saved