"""create customers table

Revision ID: 0687b342101e
Revises: 
Create Date: 2026-08-13 16:47:45.561788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0687b342101e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('email_hash', sa.String(length=128), nullable=False),
    sa.Column('signup_country', sa.String(length=2), nullable=False),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('risk_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kyc_status IN ('pending', 'verified', 'rejected')", name='ck_customers_kyc_status'),
    sa.CheckConstraint('risk_rating IS NULL OR risk_rating BETWEEN 1 AND 5', name='ck_customers_risk_rating'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
