"""add transaction account timestamp index

Revision ID: 8d93170f6a48
Revises: 643e13fa433e
Create Date: 2026-09-28 16:18:58.233377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d93170f6a48'
down_revision: Union[str, Sequence[str], None] = '643e13fa433e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_account_timestamp', 'transactions', ['account_id', 'transaction_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_account_timestamp', table_name='transactions')
    # ### end Alembic commands ###
